### PR TITLE
feature/add-init-scripts-and-logging

### PR DESCRIPTION
**Pull request by rtomsick**
Adds both support for NsCDE-specific init scripts (under `.NsCDE/init.d`) and file logging for the NsCDE startup process.

Init script support is pretty simple: anything under `.NsCDE/init.d` that's executable will be executed, in dir sort order, with its output piped to the NsCDE startup log.

Use case: starting NsCDE via a `nscde.desktop` file via a display manager that doesn't honor `.xsession` (ex: gdm on Fedora 31).  The directory-based DE init makes it easy to write and manage the various init scripts specific to NsCDE, ex: key remapping, tray applet startup, etc.

### CODE REVIEW

**Comment by NsCDE** [comment]
> Adds both support for NsCDE-specific init scripts (under `.NsCDE/init.d`) and file logging for the NsCDE startup process.
> 
> Init script support is pretty simple: anything under `.NsCDE/init.d` that's executable will be executed, in dir sort order, with its output piped to the NsCDE startup log.
> 
> Use case: starting NsCDE via a `nscde.desktop` file via a display manager that doesn't honor `.xsession` (ex: gdm on Fedora 31). The directory-based DE init makes it easy to write and manage the various init scripts specific to NsCDE, ex: key remapping, tray applet startup, etc.

Hello Rob,

Thanks for your sugestions and additions.

First, the scripts: I think that having official "init.d" is a bit too much because there are at least two ways of achieving custom commands during X session initialization:

1. Except on test systems, I myself use .xsession and simply call nscde startup script from it.
This .xsession/.xinitrc files can by nicely integrated in the most display managers (I have tested that with lightdm, gdm, sddm ...) This can be used for things which must be called before starting fvwm. There is no need to install and/or use nscde.xsession file in that case. From there, you can even call something as "init.d/*" if there is need for that.

2. FVWM itself can call things with "Exec" from $FVWM_USERDIR/NsCDE-Init.conf which is meant to be copied from $NSCDE_ROOT/config to $FVWM_USERDIR (and hence overriden and edited) anyway. This is a good place for session automatization and calling tray and such. Setxkbmap/xmodmap can ge called from here, but also from the $FVWM_USERDIR/Xset.conf (or .xsession). Anything that is put in Xset.conf will not be overwritten if it is written outside #<scriptname> and it's #end block where style managers are writing configuration. Personally, I'm calling xgamma and setxkbmap from there.

3. There is something from the freedesktop standards called $HOME/.config/autostart. NsCDE is not using this facility yet, but as soon as I read and figure out more about that, I can support it probably. It is better to have it in a standard way, then private exec/init dir.

4. Just any NsCDE-<xyz>.local or NsCDE.conf is a FVWM configuration file included by the NsCDE-Main.conf and can be armed with Exec's like minefield. :-)

I think this is more than enough for calling custom things already.

Logging: sorry but as admin and integrator with 20+ years of practice, I preffer not to log benign actions, but problematic and erroneous behaviour, because in the wood of this messages, important things can be missed and harder to spot.

Where you definitely have pointed my attention is that a main wrapper is written sparsely and it must definitely have more error checking and produce some messages in the case something is going wrong before execing final window manager. That said, I will extend nscde with that part to make it more robust and more informative. For an output, we can really use existing $HOME/.xsession-errors to have it all in one place.

**Comment by rtomsick** [comment]
All fair comments.  I wanted more organization than .xsession allowed, since obviously what you start for one DE varies from that which you need for another.  For example: I use both Xfce and NsCDE, but use different applets, etc. for each.    I didn't know about FVWM's Exec support though.  Despite being a CDE user, I'm actually pretty new to FVWM, so no surprise there...

(And for logging, well... that was more for me.  I'm in the "log lots, but filter more" camp.  No worries... it's easy enough to disable.)

Anyway, back to the task at hand:

Given that not all NsCDE users will be full-time ones, perhaps the best DE-agnostic(-ish) solution would be the Freedesktop autostart support?  From reading the spec it doesn't seem like it'd be all that hard to integrate.  (Of course to really polish it off you'd want some sort of Motif-esque manager for this.)

Would a patchset introducing support for desktop autostart be something that might get merged? ;)

**Comment by rtomsick** [comment]
Given above comments, withdrawing PR.

**Comment by NsCDE** [comment]
> All fair comments. I wanted more organization than .xsession allowed, since obviously what you start for one DE varies from that which you need for another. For example: I use both Xfce and NsCDE, but use different applets, etc. for each. I didn't know about FVWM's Exec support though. Despite being a CDE user, I'm actually pretty new to FVWM, so no surprise there...

Just copy NsCDE-Init.con in $FVWM_USERDIR and put Exec exec /my/init-d/handler in InitFunction and you get it. :)

> Given that not all NsCDE users will be full-time ones, perhaps the best DE-agnostic(-ish) solution would be the Freedesktop autostart support? From reading the spec it doesn't seem like it'd be all that hard to integrate. (Of course to really polish it off you'd want some sort of Motif-esque manager for this.)

> Would a patchset introducing support for desktop autostart be something that might get merged? ;)

I just had a look at the thing. It is messy. At least on CentOS 7 and Fedora 31. Some things are autostarted from /etc/xdg/autostart, and some from $HOME/.config/autostart. The later can be under user's control, but 90% of that from /etc/xdg/autostart is useless or gnome-centric.

The thing is called "dex", but name clashes with some editor, so it is "dex-autostart" in Fedora. Just "dnf install dex-autostart" and play with it if you want. For now, I see some things are missing from the dex (it's a python script), and it can be safe only for $HOME/.config/autostart. Maybe if I get time I can add two important things in it:

a) negation of some DE, for example -e '!GNOME' (easy)

b) AutostartCondition parsing - harder because it has sub-options and this is not mentioned anywhere in the spec as I can see.

Anyway, it can be called with Exec from NsCDE-Init, but with -s $[HOME]/.config/autostart to avoid GNOME machinery from /etc/xdg/autostart.

**Comment by rtomsick** [comment]
So it looks like `dex-autostart` plus a little FVWM Exec glue code should get us XDG autostart support... more or less.  Use `OnlyShownIn` in combination w/ the `-e` flag as you said, use `-s` to restrict it to the `$XDG_CONFIG_HOME/autostart` dir, and you're golden.

That still leaves graphical editing, but I suppose that could be a manual consideration for now.  And as an interim solution it seems pretty scriptable.

It seems like it'd be pretty easy to add in optional support for that w/ `dex-autostart`.  Would you look at a PR for that if I sent one your way?

**Comment by NsCDE** [comment]
> So it looks like `dex-autostart` plus a little FVWM Exec glue code should get us XDG autostart support... more or less. Use `OnlyShownIn` in combination w/ the `-e` flag as you said, use `-s` to restrict it to the `$XDG_CONFIG_HOME/autostart` dir, and you're golden.

Looks like that.. Blindly starting what packages drop in /etc/xdg/autostart doesn't have any sense. If there is something useful there (pnmixer, spice-vdagent ...) it can be copied in local home config autostart dir.

My opinion is that this is good for starting background processes and trigger some actions, and for tray applets which are then gathered by stalonetray or equivalent, but not for a ordinary windows such as terminal, browser, mail etc, because in FVWM, one can have more control over WHERE to put applications. There is no (easy) way to define page or workspace/desk or order from XDG autostart, in contrast to the NsCDE-Init.conf. I have updated nscde-setup to make initial copy from NSCDE_ROOT/config into FVWM_USERDIR now.

Second, OnlyShowIn: in NsCDE/FVWM case doesn't have any adventage over native execing from  user's NsCDE-Init.conf. It can be useful only for things which are common to multiple environments.

> That still leaves graphical editing, but I suppose that could be a manual consideration for now. And as an interim solution it seems pretty scriptable.
> 
> It seems like it'd be pretty easy to add in optional support for that w/ `dex-autostart`. Would you look at a PR for that if I sent one your way?

First I must think of this. How to integrate in a non-agressive and optional way, how to show this in subpanel's menu or else, when dex-autostart is not installed (it cannot be pushed as mandatory dependency).

It is still fresh. I have discovered it yesterday. I',m a fun of "think before you write code". :)

But in a principle, FvwmScript for enable, disable, create or edit this in user's autostart can be a consideration. But first the whole thing must "brew" some days or a weeks.

**Pull request closed without merging**
